M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date dom 05 fev 2023 11:25:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-05T11:25:35-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.600
%
G90
G05
T1
X178.9Y-116.75
X178.9Y-144.75
X201.1Y-130.0
T0
M30
